package fr.hydrosea.preview.application;

import fr.hydrosea.evenements.application.PortEvenements;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ServicePreview {
  private final JdbcTemplate jdbc; private final PortEvenements evenements;
  public ServicePreview(JdbcTemplate jdbc,PortEvenements evenements){this.jdbc=jdbc;this.evenements=evenements;}
  private UUID correlation(){return UUID.randomUUID();}
  private String reference(String prefixe){return prefixe+"-"+System.currentTimeMillis()+"-"+(int)(Math.random()*1000);}
  private void evenement(String type,String agregat,UUID id){evenements.enregistrer(type,agregat,id,correlation(),Map.of("identifiant",id));}
  public List<Map<String,Object>> lister(String table){return jdbc.queryForList("SELECT * FROM "+table+" WHERE date_suppression IS NULL ORDER BY date_creation DESC LIMIT 100");}
  public Map<String,Object> obtenir(String table,UUID id){return jdbc.queryForMap("SELECT * FROM "+table+" WHERE id=?",id);}
  @Transactional public Map<String,Object> creerDesserte(Map<String,Object> c){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO des.point_desserte(id,reference,statut,identifiant_commune,identifiant_adresse) VALUES (?,?, 'CREE',?,?)",id,reference("PD"),UUID.fromString(c.get("identifiant_commune").toString()),UUID.fromString(c.get("identifiant_adresse").toString()));evenement("POINT_DESSERTE_CREE","POINT_DESSERTE",id);return obtenir("des.point_desserte",id);}
  @Transactional public Map<String,Object> disponibiliser(UUID id,int version){int n=jdbc.update("UPDATE des.point_desserte SET statut='DISPONIBLE',version=version+1 WHERE id=? AND version=?",id,version);if(n==0)throw new VersionObsolete();evenement("POINT_DESSERTE_DISPONIBLE","POINT_DESSERTE",id);return obtenir("des.point_desserte",id);}
  @Transactional public Map<String,Object> creerConsommation(Map<String,Object> c){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO des.point_consommation(id,reference,usage,identifiant_adresse) VALUES (?,?,?,?)",id,reference("PC"),c.get("usage"),UUID.fromString(c.get("identifiant_adresse").toString()));evenement("POINT_CONSOMMATION_CREE","POINT_CONSOMMATION",id);if(c.get("identifiant_point_desserte")!=null)rattacher(id,UUID.fromString(c.get("identifiant_point_desserte").toString()),OffsetDateTime.now());return obtenir("des.point_consommation",id);}
  @Transactional public Map<String,Object> rattacher(UUID pc,UUID pd,OffsetDateTime debut){String statut=jdbc.queryForObject("SELECT statut FROM des.point_desserte WHERE id=?",String.class,pd);if(!"DISPONIBLE".equals(statut))throw new RegleMetier("La desserte doit être disponible.");UUID id=UUID.randomUUID();jdbc.update("INSERT INTO des.liaison_desserte_consommation(id,point_desserte_id,point_consommation_id,periode) VALUES (?,?,?,tstzrange(?,NULL,'[)'))",id,pd,pc,debut);evenement("RATTACHEMENT_CREE","POINT_CONSOMMATION",pc);return obtenir("des.point_consommation",pc);}
  @Transactional public Map<String,Object> ouvrir(UUID id,int version){Integer n=jdbc.queryForObject("SELECT count(*) FROM des.liaison_desserte_consommation l JOIN des.point_desserte d ON d.id=l.point_desserte_id WHERE l.point_consommation_id=? AND l.periode @> now() AND d.statut='DISPONIBLE'",Integer.class,id);if(n==0)throw new RegleMetier("Un rattachement à une desserte disponible est requis.");if(jdbc.update("UPDATE des.point_consommation SET statut='OUVERT',version=version+1 WHERE id=? AND version=?",id,version)==0)throw new VersionObsolete();evenement("POINT_CONSOMMATION_OUVERT","POINT_CONSOMMATION",id);return obtenir("des.point_consommation",id);}
  @Transactional public Map<String,Object> creerContrat(Map<String,Object> c){UUID id=UUID.randomUUID(),pc=UUID.fromString(c.get("identifiant_point_consommation").toString());jdbc.update("INSERT INTO abo.contrat_abonnement(id,reference,point_consommation_id,nature_abonnement,date_demande,date_effet) VALUES (?,?,?,?,?,?)",id,reference("CA"),pc,c.get("nature_abonnement"),LocalDate.parse(c.get("date_demande").toString()),LocalDate.parse(c.get("date_effet_souhaitee").toString()));evenement("CONTRAT_CREE","CONTRAT",id);return obtenir("abo.contrat_abonnement",id);}
  @Transactional public Map<String,Object> ajouterParticipant(UUID contrat,Map<String,Object> c){UUID id=UUID.randomUUID();boolean principal="TITULAIRE_PRINCIPAL".equals(c.get("role_contractuel"));jdbc.update("INSERT INTO abo.participation_contrat(id,contrat_id,tiers_id,role_contractuel,principal,responsabilite_financiere,periode) VALUES (?,?,?,?,?,?,daterange(?,NULL,'[)'))",id,contrat,UUID.fromString(c.get("identifiant_tiers").toString()),c.get("role_contractuel"),principal,c.getOrDefault("responsabilite_financiere",true),LocalDate.parse(c.get("date_debut_validite").toString()));evenement("PARTICIPANT_AJOUTE","CONTRAT",contrat);return jdbc.queryForMap("SELECT * FROM abo.participation_contrat WHERE id=?",id);}
  @Transactional public Map<String,Object> valider(UUID id,int version){Integer n=jdbc.queryForObject("SELECT count(*) FROM abo.participation_contrat WHERE contrat_id=? AND principal AND upper_inf(periode)",Integer.class,id);if(n!=1)throw new RegleMetier("Un titulaire principal actif est requis.");if(jdbc.update("UPDATE abo.contrat_abonnement SET statut='VALIDE',version=version+2 WHERE id=? AND version=? AND statut='BROUILLON'",id,version)==0)throw new VersionObsolete();evenement("CONTRAT_A_VALIDER","CONTRAT",id);evenement("CONTRAT_VALIDE","CONTRAT",id);return obtenir("abo.contrat_abonnement",id);}
  @Transactional public Map<String,Object> activer(UUID id,int version){Integer n=jdbc.queryForObject("SELECT count(*) FROM abo.contrat_abonnement c JOIN des.point_consommation p ON p.id=c.point_consommation_id WHERE c.id=? AND c.statut='VALIDE' AND p.statut='OUVERT'",Integer.class,id);if(n!=1)throw new RegleMetier("Le Contrat doit être validé et le Point ouvert.");if(jdbc.update("UPDATE abo.contrat_abonnement SET statut='ACTIF',version=version+1 WHERE id=? AND version=?",id,version)==0)throw new VersionObsolete();evenement("CONTRAT_ACTIVE","CONTRAT",id);return obtenir("abo.contrat_abonnement",id);}
  @Transactional public Map<String,Object> enregistrerCompteur(Map<String,Object> c){UUID id=UUID.randomUUID();String numero=c.get("numero_serie").toString().strip().toUpperCase();jdbc.update("INSERT INTO cpt.compteur(id,numero_serie,fabricant,modele,calibre) VALUES (?,?,?,?,?)",id,numero,c.get("fabricant"),c.get("modele"),c.get("calibre"));evenement("COMPTEUR_ENREGISTRE","COMPTEUR",id);return obtenir("cpt.compteur",id);}
  @Transactional public Map<String,Object> poser(UUID id,int version,Map<String,Object> c){UUID pc=UUID.fromString(c.get("identifiant_point_consommation").toString());Integer existe=jdbc.queryForObject("SELECT count(*) FROM des.point_consommation WHERE id=?",Integer.class,pc);if(existe==0)throw new RegleMetier("Point de consommation absent.");if(jdbc.update("UPDATE cpt.compteur SET statut='POSE',version=version+1 WHERE id=? AND version=? AND statut='DISPONIBLE'",id,version)==0)throw new VersionObsolete();UUID a=UUID.randomUUID();jdbc.update("INSERT INTO cpt.affectation_compteur(id,compteur_id,point_consommation_id,periode,index_pose,reference_intervention) VALUES (?,?,?,tstzrange(?,NULL,'[)'),?,?)",a,id,pc,OffsetDateTime.parse(c.get("date_pose").toString()),c.get("index_pose"),c.get("reference_intervention"));evenement("COMPTEUR_POSE","COMPTEUR",id);evenement("AFFECTATION_CREEE","AFFECTATION_COMPTEUR",a);return obtenir("cpt.compteur",id);}
  public List<Map<String,Object>> activite(UUID pc){return jdbc.queryForList("SELECT type_evenement,date_metier,type_agregat,agregat_id FROM evt.evenement_metier WHERE agregat_id=? OR agregat_id IN (SELECT id FROM abo.contrat_abonnement WHERE point_consommation_id=? UNION SELECT compteur_id FROM cpt.affectation_compteur WHERE point_consommation_id=?) ORDER BY date_metier DESC LIMIT 30",pc,pc,pc);}
  public static class RegleMetier extends RuntimeException{public RegleMetier(String m){super(m);}}
  public static class VersionObsolete extends RuntimeException{}
}
